# general
batch_size: 32
optimizer: sgd
patience: 50
architecture: longfilter
in_channels: 1
max_epoch: 300
exp_name: densenet_small_winlen_256
pretrained: true
normalize_spectrums: true 
learning_rate: 0.01
window_len: 256
spec_type: librosa_melspec
dev_step_size: 32
size: 10
seed: 42

# Metadata splits
metadata_fname: '/home/jerpint/Dropbox/voicemd_db/cv_balanced/cv_metadata_balanced_clean.csv'
# metadata_fname: '../data/voice_clips/cleaned_metadata_filtered_dysphonia.csv'
split_type: shuffled_kfold
n_splits: 10
